project_identifier: ezplatform
files:
  - source: /ezpublish-kernel/*.xlf
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /repository-forms/*.xlf
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /ezplatform-admin-ui/*.xlf
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /date-based-publisher/*
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /flex-workflow/*
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /ezplatform-page-fieldtype/*
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /ezplatform-page-builder/*
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /ezplatform-admin-ui-modules
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
  - source: /ezplatform-form-builder/*.xlf
    translation: >-
      /translations/%locale_with_underscore%/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%
